config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get  '/shops/search' => 'shops#top'
  post '/shops/search' => 'shops#search'
  resources :shops
  root 'shops#top'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search
  include ActiveModel::Model
  #include ActiveModel::EachValidator
  attr_accessor :date, :time
  validate :date_valid?

end

def date_valid?
  return if date.blank?
  convertDate = date.delete("-")
  y = convertDate[0, 4].to_i
  m = convertDate[4, 2].to_i
  d = convertDate[6, 2].to_i
  unless Date.valid_date?(y, m, d)
    errors.add(:date, "日付の値が不正です")
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :shop_places
  has_many :places, through: :shop_places
  validates :name,
    presence: true
  validates :price,
    numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :url,
    allow_blank: true,
    format: /\A#{URI::regexp(%w(http https))}\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  before_action :find_shop, only: [:edit, :update, :destroy]

  def top
    @search = Search.new
    @search.date = Date.today.to_s
    @search.time = '1'
    @shops = nil
  end

  def search
    @search = Search.new(search_params)
    unless @search.valid?
       return render 'top'
    end
    @shops = search_shops
    render 'top'
  end

  def index
    @shops = Shop.all.order('id')
  end

  def create
    logger.debug(shop_params)
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to shops_path
    else
      render 'new'
    end
  end

  def new
    @shop = Shop.new
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      redirect_to shops_path
    else
      render 'edit'
    end
  end

  def destroy
    @shop.destroy
    redirect_to shops_path
  end

  private

  def shop_params
    params[:shop].permit(:name, :price, :url, :mon1, :mon2, :tue1, :tue2, :wed1, :wed2, :thu1, :thu2, :fri1, :fri2, :sat1, :sat2, :sun1, :sun2, :hol1, :hol2)
  end

  def search_params
    params[:search].permit(:date, :time)
  end

  def search_shops
    # 曜日チェック
    wdays = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"]
    d = Date.strptime(@search.date, "%Y-%m-%d")
    str = ""
    if HolidayJp.holiday?(d)
      str = "hol" + @search.time.to_s + ' = TRUE'
    else
      str = wdays[d.wday] + @search.time.to_s + ' = TRUE'
    end
    Shop.where(str).order('id')
  end

  def find_shop
    @shop = Shop.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TreasureSearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <br>
    <%= link_to "Home", "/" %>
    <%= link_to "店舗一覧", "/shops" %>
  </body>
</html>

app/views/shops/_form.erb
<%= form_for @shop do |f| %>
  <% if @shop.errors.any? %>
    <% @shop.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :price %><br>
    <%= f.text_field :price %>円
  </div>
  <div>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div>
    <table>
      <tr>
        <th>営業時間</th>
        <th>日曜日</th>
        <th>月曜日</th>
        <th>火曜日</th>
        <th>水曜日</th>
        <th>木曜日</th>
        <th>金曜日</th>
        <th>土曜日</th>
        <th>祝日</th>
      </tr>
      <tr>
        <th>昼の部</th>
        <td><%= f.check_box :sun1 %></td>
        <td><%= f.check_box :mon1 %></td>
        <td><%= f.check_box :tue1 %></td>
        <td><%= f.check_box :wed1 %></td>
        <td><%= f.check_box :thu1 %></td>
        <td><%= f.check_box :fri1 %></td>
        <td><%= f.check_box :sat1 %></td>
        <td><%= f.check_box :hol1 %></td>
      </tr>
      <tr>
        <th>夜の部</th>
        <td><%= f.check_box :sun2 %></td>
        <td><%= f.check_box :mon2 %></td>
        <td><%= f.check_box :tue2 %></td>
        <td><%= f.check_box :wed2 %></td>
        <td><%= f.check_box :thu2 %></td>
        <td><%= f.check_box :fri2 %></td>
        <td><%= f.check_box :sat2 %></td>
        <td><%= f.check_box :hol2 %></td>
      </tr>
    </table>
  </div>
  <div>
  <div>
  <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h3>店舗追加</h3>

<%= render 'form' %>

app/views/shops/index.html.erb
<h3>All Shops</h3>
<%= link_to "店舗追加", new_shop_path %>
<% unless @shops.empty? %>
  <table>
    <thead>
      <tr>
        <th>店名</th>
        <th>小・値段</th>
        <th>URL</th>
        <th>更新</th>
        <th>削除</th>
      </tr>
    </thead>
    <tbody>
      <% @shops.each do |shop| %>
        <tr>
          <td><%= shop.name %></td>
          <td><%= shop.price %></td>
          <td><%= link_to "リンク", shop.url %></td>
          <td><%= link_to "更新", edit_shop_path(shop.id) %></td>
          <td><%= link_to "削除", shop_path(shop.id), method: :delete,
          data: {confirm: "削除してよろしいですか？"} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/shops/new.html.erb
<h3>店舗追加</h3>

<%= render 'form' %>

app/views/shops/top.html.erb
<h3>検索画面</h3>

<%= form_for @search, url: '/shops/search', method: :post do |f| %>
  <%# 日付 %>
  <p>
    <%= f.label :date , '来訪日:' %><br>
    <%= f.text_field :date %>
  </p>

  <%# 昼・夜 %>
  <p>
    <%= f.label :time, '昼・夜:' %><br>
    <%= f.radio_button :time, '1', {:checked => @search.time == '1'} %>昼の部<br>
    <%= f.radio_button :time, '2', {:checked => @search.time == '2'} %>夜の部<br>
  </p>
  <p>
    <%= f.submit '検索' %>
  </p>

  <%# 店舗一覧 %>
  <% unless @shops.nil? %>
    <% if @shops.count == 0 %>
      <p>店舗が見つかりません</p>
    <% else %>
      <table>
        <thead>
          <tr>
            <th>店名</th>
            <th>小・値段</th>
            <th>URL</th>
          </tr>
        </thead>
        <tbody>
          <% @shops.each do |shop| %>
            <tr>
              <td><%= shop.name %></td>
              <td><%= shop.price %>円</td>
              <td><%= link_to "リンク", shop.url %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  <% end %>
<% end %>